name: 友链模板
description: 提交友链意向申请。
labels: ['审核中']
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 检查清单
      description: 请认真检查以下清单中的每一项，并在相符的项前打勾。（在真实满足所有条件后才会通过，不满足的项请不要勾选）
      options:
        - required: true
          label: 合法的、非营利性、无商业广告、无木马植入。
        - required: true
          label: 承诺不会对友链进行高频次爬取（若一次性爬取多个页面，则1天不超过1次；若仅访问feed地址，则1小时不超过1次），爬取过于频繁会被认为存在木马嫌疑。
        - required: false
          label: 有实质性原创内容的 HTTPS 站点，发布过至少 10 篇原创文章，内容题材不限。
        - required: false
          label: 有独立域名，非免费域名。（在真实满足后才会通过，不满足时请不要勾选）
        - required: false
          label: 博客已持续运行至少3年。（在真实满足后才会通过，不满足时请不要勾选）
        - required: false
          label: 先友后链：与博主有至少**1年**的双向有效互动，例如互相留言评论、issue、PR等。（在真实满足后才会通过，不满足时请不要勾选）
  - type: textarea
    id: json-data
    validations:
      required: true
    attributes:
      label: 友链信息
      description: 请在双引号中填写，不要修改格式。
      value: |
        <!--
        请在下方的 `JSON` 块中填写，字段说明：
        - title: 友链标题
        - url: 友链地址
        - icon: 网站图标
        - snapshot: 网站截图
        - description: 一句话简介
        - feed: 订阅地址（抓取并显示最新文章，没有 feed 地址时，排序会靠后）
        -->
        
        ```json
        {
            "title": "",
            "url": "",
            "icon": "",
            "snapshot": "",
            "description": "",
            "feed": ""
        }
        ```

        
  - type: input
    id: friends-html
    attributes:
      label: 友链地址
      description: 请输入您的友链页面地址，用于人工审核和 GitHub Actions 自动检测。（不必提前添加本站为友链，审核通过后再添加也不迟。）
      placeholder: "如: https://xaoxuu.com/friends/"
    validations:
      required: true
  - type: input
    id: friends-repo
    attributes:
      label: 友链仓库（可选）
      description: 如果您使用 issue 作为友链源，请附上 issue 仓库链接，博主将会前往您的仓库自行填写友链。
      placeholder: "如: https://github.com/xaoxuu/friends/"
